### PR TITLE
Winter 21 changes

### LINKED ISSUE #1: Winter 21: Migrate to SObject.getErrors methods
## Expected Behavior

Safe harbor, but seems likely to be included in Winter 21: https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_apex_trackErrors.htm - this allows us to replace the usage of `ApexPages.getMessages()` with the new `.getErrors()` method on SObjects:

* In [MetadataTriggerHandlerTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/base/main/default/classes/MetadataTriggerHandlerTest.cls)
* In [ta_Opportunity_StageChangeRulesTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls)
* In [ta_Opportunity_StageInsertRulesTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRulesTest.cls)
* And in the good old [Readme](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/README.md)

## Actual Behavior

`ApexPages` methods are used

## Notes

Happy to submit a PR for this after Winter 21 is released!

### PR DESCRIPTION
**Pull request by jamessimone**
Fixes #1 

A few things to note:

- I followed the advice in the Contributing.md and filled out my CLA
- There's an unusual amount of whitespace in each file. I'm not sure if this is intended or not, but I had to make my changes in Notepad because even with VS Code's "Format On Save" option turned off (and with Prettier disabled, as well as the VS Code settings related to trimming whitespace), my original diff was still misrepresented as a total file rewrite :(
- At least on the generated diff prior to submitting the PR, I am being told that `application/opportunity-automation/main/default/customMetadata/Trigger_Action.ta_Opportunity_SendWonNotification.md-meta.xml` has been deleted, though this was not part of any `git diff` I saw prior to committing and pushing. Not sure what that's about and  `git checkout origin/master -- application/opportunity-automation/main/default/customMetadata/Trigger_Action.ta_Opportunity_SendWonNotification.md-meta.xml` failed, which is my norm for reverting a phantom change like this with: `error: pathspec 'application/opportunity-automation/main/default/customMetadata/Trigger_Action.ta_Opportunity_SendWonNotification.md-meta.xml' did not match any file(s) known to git`

### CODE REVIEW

**Comment by jamessimone** [comment]
@mitchspano just my luck to have submitted this while you were also making changes! I will rebase and re-push

**Comment by mitchspano** [comment]
Sorry! Less than ideal timing.
The whitespace is not intended, I will take a look into that.
The deletion of `TriggerAction. ta_Opportunity_SendWonNotification.md-meta.xml` was intentional. It was a leftover artifact from some previous tests. Just remove it from you PR and everything should be good.

**Comment by jamessimone** [comment]
No worries, almost done updating

**Comment by mitchspano** [comment]
Also,
If we are trying to make this compatible with Winter 21, we might want to update the API version to 50.0 in all classes and `sfdx-project.json`.

**Comment by jamessimone** [comment]
@mitchspano I added in all of the API version updates, however the `MetadataTriggerHandler` and its test file still have some messed up diffs. Working on that now.

**Comment by jamessimone** [comment]
@mitchspano should be ready to review now. Apologies for the in-between on looking at those diffs - we crossed the streams!

**Comment by mitchspano** [comment]
When I try to checkout and deploy from this PR, I get some sdfx deployment errors:
```
On branch pr/2
Your branch is up to date with 'github-desktop-jamessimone/feature/winter21'.

nothing to commit, working tree clean
macbook-pro-2:apex-trigger-actions-framework mitchellspano$ sfdx force:source:push
Job ID | 0Af3B00001BvnRnSAJ
SOURCE PROGRESS | ████████████████████████████████████████ | 31/31 Components
Job ID | 0Af3B00001BvnSRSAZ
SOURCE PROGRESS | ██████████████████████████████░░░░░░░░░░ | 6/8 Components
TYPE   PROJECT PATH                                                                                     PROBLEM
─────  ───────────────────────────────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────────────────────────────────────
Error  application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls  Extra ';', at ')'. (32:56)
Error  application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls  Comparison arguments must be compatible types: Integer, List<Database.Error> (32:10)
ERROR running force:source:push:  Push failed. 
```

**Comment by jamessimone** [comment]
Updated - should be good now

**Comment by mitchspano** [comment]
Everything is able to deploy, but there is a test failure:

```
MetadataTriggerHandlerTest
afterInsert_fail
Fail
System.AssertException: Assertion Failed: Expected: true, Actual: false
Class.MetadataTriggerHandlerTest.afterInsert_fail: line 189, column 1
```

**Comment by jamessimone** [comment]
@mitchspano apologies. This whole "developing in notepad" thing made me sloppy, I missed one crucial account reference and of course that issue with the parenthesis. Everything should be good now, all tests passing.

**Comment by mitchspano** [comment]
Looks good.

**Comment by jamessimone** [comment]
Thanks! And thanks again for this library.

**Pull request merged**
