### PR TITLE
Bug fix for issue #54

### LINKED ISSUE #54: Illegal assignment from java:moduleapi.interaction.Flow(Multi-)PicklistValue to String
## Expected Behavior

Assigning values to picklist or multipicklist fields in autolaunched flows for this framework should not throw an error if flow finishes and values are processed in TriggerActionFlow.applyFlowValues.

## Actual Behavior

One of the following errors is thrown if a value is set to either a picklist field or a multipicklist field:
- Illegal assignment from java:moduleapi.interaction.FlowPicklistValue to String
- Illegal assignment from java:moduleapi.interaction.FlowMultiPicklistValue to String

## Steps to Reproduce the Problem

1. Create an autolaunched flow as described in README.md which populates a picklist or multipicklist field with a valid value.
2. Invoke flow by trying to save a record.

### PR DESCRIPTION
**Pull request by benjaminloerincz**
Fixes #54

- [X] Tests pass: Done
- [X] Appropriate changes to README are included in PR: No need

### CODE REVIEW

**Comment by mitchspano** [comment]
This is looking great Ben, thank you!

I do think that we should write a unit test for this functionality within TriggerActionFlowTest though. We could us Case.Status for the single select picklists, but I am unaware of any out of the box multiple select picklists which could cover that logic.

**Comment by benjaminloerincz** [comment]
For the multipicklist I found these in the Salesforce object reference:
- AccountContactRelation.Roles
- CommissionSchedule.ApplicableObject
- CommissionScheduleAssignment.CommissionableEventType
- Idea.Categories
- IdeaTheme.Categories
- QuickText.Channel
- WorkTypeGroup.AdditionalInformation

I think the QuickText object will do the job. What do you think?

**Comment by mitchspano** [comment]
Hey @benjaminloerincz , can we resolve these merge conflicts and write a unit test with `QuickText.Channel` to make sure the changes for multi-select picklists works as expected? Then we can merge this PR.

Thanks!

**Comment by benjaminloerincz** [comment]
I just reanalyzed the original error and found that the error no longer occurs. I suspect that this has to do with the change from oldList/newList/newListAfterFlow to triggerRecords. So the coding can stay as it is. I close this pull request and leave the metadata created for analysis as is in my branch.

**Comment by mitchspano** [comment]
Cool - a free fix; gotta love that.
Thanks for the update Benjamin!

**Pull request closed without merging**
